---
- name: Install sendmail
  package:
    name: sendmail
    state: present
  tags:
    - install

- name: Install sendmail
  package:
    name: sendmail-cf
    state: present
  tags:
    - install
  when: ansible_distribution == 'OracleLinux' or ansible_distribution == 'RedHat'
